platform :ios, '10.0'

target 'SimpleMeal' do
  use_frameworks!

pod 'TwitterKit'

  target 'SimpleMealTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleMealUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
